/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICWallet,
  ICWalletInterface,
} from "../../../contracts/interfaces/ICWallet";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "theTargets",
        type: "address[]",
      },
    ],
    name: "blacklistTargets",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "theTargets",
        type: "address[]",
      },
    ],
    name: "whitelistTargets",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdrawNative",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICWallet__factory {
  static readonly abi = _abi;
  static createInterface(): ICWalletInterface {
    return new Interface(_abi) as ICWalletInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICWallet {
    return new Contract(address, _abi, runner) as unknown as ICWallet;
  }
}
