/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aa from "./AA";
export type { aa };
export type { ICWallet } from "./ICWallet";
export type { ICollective } from "./ICollective";
export type { IPool } from "./IPool";
