/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "distributeReward"
      | "getParticipantsCount"
      | "getPoolInfo"
      | "recordMint"
      | "withdrawReward"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "NewMint"
      | "NewParticipant"
      | "RewardDistributed"
      | "RewardReceived"
      | "RewardWithdrawn"
      | "WithrawnToCollective"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "distributeReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipantsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordMint",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawReward",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "distributeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipantsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recordMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawReward",
    data: BytesLike
  ): Result;
}

export namespace NewMintEvent {
  export type InputTuple = [
    participant: AddressLike,
    tokenID: BigNumberish,
    quantity: BigNumberish,
    amountPaid: BigNumberish
  ];
  export type OutputTuple = [
    participant: string,
    tokenID: bigint,
    quantity: bigint,
    amountPaid: bigint
  ];
  export interface OutputObject {
    participant: string;
    tokenID: bigint;
    quantity: bigint;
    amountPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewParticipantEvent {
  export type InputTuple = [participant: AddressLike];
  export type OutputTuple = [participant: string];
  export interface OutputObject {
    participant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [participant: AddressLike, amount: BigNumberish];
  export type OutputTuple = [participant: string, amount: bigint];
  export interface OutputObject {
    participant: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardReceivedEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardWithdrawnEvent {
  export type InputTuple = [participant: AddressLike, amount: BigNumberish];
  export type OutputTuple = [participant: string, amount: bigint];
  export interface OutputObject {
    participant: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithrawnToCollectiveEvent {
  export type InputTuple = [
    to: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [to: string, token: string, amount: bigint];
  export interface OutputObject {
    to: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPool extends BaseContract {
  connect(runner?: ContractRunner | null): IPool;
  waitForDeployment(): Promise<this>;

  interface: IPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  distributeReward: TypedContractMethod<[], [void], "nonpayable">;

  getParticipantsCount: TypedContractMethod<[], [bigint], "view">;

  getPoolInfo: TypedContractMethod<
    [],
    [
      [string, bigint, bigint, bigint, boolean, boolean] & {
        _tokenContract: string;
        _reward: bigint;
        _rewardDistributed: bigint;
        _totalContributions: bigint;
        _isRewardReceived: boolean;
        _isDistributed: boolean;
      }
    ],
    "view"
  >;

  recordMint: TypedContractMethod<
    [
      _participant: AddressLike,
      _tokenID: BigNumberish,
      _quantity: BigNumberish,
      _amountPaid: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  withdrawReward: TypedContractMethod<
    [_participant: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "distributeReward"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getParticipantsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPoolInfo"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, bigint, bigint, boolean, boolean] & {
        _tokenContract: string;
        _reward: bigint;
        _rewardDistributed: bigint;
        _totalContributions: bigint;
        _isRewardReceived: boolean;
        _isDistributed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordMint"
  ): TypedContractMethod<
    [
      _participant: AddressLike,
      _tokenID: BigNumberish,
      _quantity: BigNumberish,
      _amountPaid: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawReward"
  ): TypedContractMethod<[_participant: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "NewMint"
  ): TypedContractEvent<
    NewMintEvent.InputTuple,
    NewMintEvent.OutputTuple,
    NewMintEvent.OutputObject
  >;
  getEvent(
    key: "NewParticipant"
  ): TypedContractEvent<
    NewParticipantEvent.InputTuple,
    NewParticipantEvent.OutputTuple,
    NewParticipantEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;
  getEvent(
    key: "RewardReceived"
  ): TypedContractEvent<
    RewardReceivedEvent.InputTuple,
    RewardReceivedEvent.OutputTuple,
    RewardReceivedEvent.OutputObject
  >;
  getEvent(
    key: "RewardWithdrawn"
  ): TypedContractEvent<
    RewardWithdrawnEvent.InputTuple,
    RewardWithdrawnEvent.OutputTuple,
    RewardWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "WithrawnToCollective"
  ): TypedContractEvent<
    WithrawnToCollectiveEvent.InputTuple,
    WithrawnToCollectiveEvent.OutputTuple,
    WithrawnToCollectiveEvent.OutputObject
  >;

  filters: {
    "NewMint(address,uint256,uint256,uint256)": TypedContractEvent<
      NewMintEvent.InputTuple,
      NewMintEvent.OutputTuple,
      NewMintEvent.OutputObject
    >;
    NewMint: TypedContractEvent<
      NewMintEvent.InputTuple,
      NewMintEvent.OutputTuple,
      NewMintEvent.OutputObject
    >;

    "NewParticipant(address)": TypedContractEvent<
      NewParticipantEvent.InputTuple,
      NewParticipantEvent.OutputTuple,
      NewParticipantEvent.OutputObject
    >;
    NewParticipant: TypedContractEvent<
      NewParticipantEvent.InputTuple,
      NewParticipantEvent.OutputTuple,
      NewParticipantEvent.OutputObject
    >;

    "RewardDistributed(address,uint256)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;

    "RewardReceived(address,uint256)": TypedContractEvent<
      RewardReceivedEvent.InputTuple,
      RewardReceivedEvent.OutputTuple,
      RewardReceivedEvent.OutputObject
    >;
    RewardReceived: TypedContractEvent<
      RewardReceivedEvent.InputTuple,
      RewardReceivedEvent.OutputTuple,
      RewardReceivedEvent.OutputObject
    >;

    "RewardWithdrawn(address,uint256)": TypedContractEvent<
      RewardWithdrawnEvent.InputTuple,
      RewardWithdrawnEvent.OutputTuple,
      RewardWithdrawnEvent.OutputObject
    >;
    RewardWithdrawn: TypedContractEvent<
      RewardWithdrawnEvent.InputTuple,
      RewardWithdrawnEvent.OutputTuple,
      RewardWithdrawnEvent.OutputObject
    >;

    "WithrawnToCollective(address,address,uint256)": TypedContractEvent<
      WithrawnToCollectiveEvent.InputTuple,
      WithrawnToCollectiveEvent.OutputTuple,
      WithrawnToCollectiveEvent.OutputObject
    >;
    WithrawnToCollective: TypedContractEvent<
      WithrawnToCollectiveEvent.InputTuple,
      WithrawnToCollectiveEvent.OutputTuple,
      WithrawnToCollectiveEvent.OutputObject
    >;
  };
}
