/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockCWalletSol from "./MockCWallet.sol";
export * as mockCollectiveSol from "./MockCollective.sol";
export { MockTokenContract__factory } from "./MockTokenContract__factory";
