/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ICWalletInterface extends Interface {
  getFunction(
    nameOrSignature: "blacklistTargets" | "whitelistTargets" | "withdrawNative"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "blacklistTargets",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistTargets",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawNative",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "blacklistTargets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistTargets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawNative",
    data: BytesLike
  ): Result;
}

export interface ICWallet extends BaseContract {
  connect(runner?: ContractRunner | null): ICWallet;
  waitForDeployment(): Promise<this>;

  interface: ICWalletInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  blacklistTargets: TypedContractMethod<
    [theTargets: AddressLike[]],
    [void],
    "nonpayable"
  >;

  whitelistTargets: TypedContractMethod<
    [theTargets: AddressLike[]],
    [void],
    "nonpayable"
  >;

  withdrawNative: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "blacklistTargets"
  ): TypedContractMethod<[theTargets: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "whitelistTargets"
  ): TypedContractMethod<[theTargets: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawNative"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
