/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockCWalletSol from "./MockCWallet.sol";
export type { mockCWalletSol };
import type * as mockCollectiveSol from "./MockCollective.sol";
export type { mockCollectiveSol };
export type { MockTokenContract } from "./MockTokenContract";
