/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as collectiveFatorySol from "./CollectiveFatory.sol";
export type { collectiveFatorySol };
export type { EscrowFactory } from "./EscrowFactory";
export type { HoneyPotFactory } from "./HoneyPotFactory";
