/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface CollectiveInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "blacklistTargets"
      | "cWallet"
      | "createPools"
      | "initialize"
      | "initiator"
      | "inviteIds"
      | "joinCollective"
      | "leaveCollective"
      | "members"
      | "operator"
      | "pools"
      | "proxiableUUID"
      | "receivePoolReward"
      | "recordPoolMint"
      | "removeMember"
      | "renounceOperator"
      | "setWallet"
      | "upgradeToAndCall"
      | "whitelistTargets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CWalletSet"
      | "CollectiveInitialized"
      | "Initialized"
      | "MemberRemoved"
      | "NewMember"
      | "OperatorRenounced"
      | "PoolAdded"
      | "RewardForwarded"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistTargets",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(functionFragment: "cWallet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createPools",
    values: [AddressLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "initiator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "inviteIds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinCollective",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "leaveCollective",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "members",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(functionFragment: "pools", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receivePoolReward",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPoolMint",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeMember",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOperator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistTargets",
    values: [AddressLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistTargets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initiator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "inviteIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "joinCollective",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leaveCollective",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receivePoolReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPoolMint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setWallet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistTargets",
    data: BytesLike
  ): Result;
}

export namespace CWalletSetEvent {
  export type InputTuple = [cWallet: AddressLike];
  export type OutputTuple = [cWallet: string];
  export interface OutputObject {
    cWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CollectiveInitializedEvent {
  export type InputTuple = [initiator: AddressLike, operator: AddressLike];
  export type OutputTuple = [initiator: string, operator: string];
  export interface OutputObject {
    initiator: string;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberRemovedEvent {
  export type InputTuple = [member: AddressLike];
  export type OutputTuple = [member: string];
  export interface OutputObject {
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewMemberEvent {
  export type InputTuple = [member: AddressLike];
  export type OutputTuple = [member: string];
  export interface OutputObject {
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorRenouncedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolAddedEvent {
  export type InputTuple = [
    pool: AddressLike,
    tokenContract: AddressLike,
    honeyPot: AddressLike,
    initiator: AddressLike
  ];
  export type OutputTuple = [
    pool: string,
    tokenContract: string,
    honeyPot: string,
    initiator: string
  ];
  export interface OutputObject {
    pool: string;
    tokenContract: string;
    honeyPot: string;
    initiator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardForwardedEvent {
  export type InputTuple = [
    pool: AddressLike,
    honeyPot: AddressLike,
    amount: BigNumberish,
    tokenContract: AddressLike
  ];
  export type OutputTuple = [
    pool: string,
    honeyPot: string,
    amount: bigint,
    tokenContract: string
  ];
  export interface OutputObject {
    pool: string;
    honeyPot: string;
    amount: bigint;
    tokenContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Collective extends BaseContract {
  connect(runner?: ContractRunner | null): Collective;
  waitForDeployment(): Promise<this>;

  interface: CollectiveInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  blacklistTargets: TypedContractMethod<
    [_targets: AddressLike[]],
    [void],
    "nonpayable"
  >;

  cWallet: TypedContractMethod<[], [string], "view">;

  createPools: TypedContractMethod<
    [_tokenContracts: AddressLike[], _honeyPots: AddressLike[]],
    [void],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [
      theInitiator: AddressLike,
      theOperator: AddressLike,
      theFactory: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  initiator: TypedContractMethod<[], [string], "view">;

  inviteIds: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  joinCollective: TypedContractMethod<
    [_inviteSig: BytesLike, _inviteId: BytesLike],
    [void],
    "nonpayable"
  >;

  leaveCollective: TypedContractMethod<[], [void], "nonpayable">;

  members: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  operator: TypedContractMethod<[], [string], "view">;

  pools: TypedContractMethod<
    [arg0: AddressLike],
    [[string, string] & { id: string; tokenContract: string }],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  receivePoolReward: TypedContractMethod<
    [_honeyPot: AddressLike],
    [boolean],
    "payable"
  >;

  recordPoolMint: TypedContractMethod<
    [
      _pool: AddressLike,
      _participant: AddressLike,
      _tokenID: BigNumberish,
      _quantity: BigNumberish,
      _amountPaid: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  removeMember: TypedContractMethod<
    [_member: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOperator: TypedContractMethod<[], [void], "nonpayable">;

  setWallet: TypedContractMethod<
    [theWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  whitelistTargets: TypedContractMethod<
    [_targets: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "blacklistTargets"
  ): TypedContractMethod<[_targets: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createPools"
  ): TypedContractMethod<
    [_tokenContracts: AddressLike[], _honeyPots: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      theInitiator: AddressLike,
      theOperator: AddressLike,
      theFactory: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initiator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "inviteIds"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "joinCollective"
  ): TypedContractMethod<
    [_inviteSig: BytesLike, _inviteId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "leaveCollective"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "members"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pools"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[string, string] & { id: string; tokenContract: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receivePoolReward"
  ): TypedContractMethod<[_honeyPot: AddressLike], [boolean], "payable">;
  getFunction(
    nameOrSignature: "recordPoolMint"
  ): TypedContractMethod<
    [
      _pool: AddressLike,
      _participant: AddressLike,
      _tokenID: BigNumberish,
      _quantity: BigNumberish,
      _amountPaid: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeMember"
  ): TypedContractMethod<[_member: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOperator"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWallet"
  ): TypedContractMethod<[theWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "whitelistTargets"
  ): TypedContractMethod<[_targets: AddressLike[]], [void], "nonpayable">;

  getEvent(
    key: "CWalletSet"
  ): TypedContractEvent<
    CWalletSetEvent.InputTuple,
    CWalletSetEvent.OutputTuple,
    CWalletSetEvent.OutputObject
  >;
  getEvent(
    key: "CollectiveInitialized"
  ): TypedContractEvent<
    CollectiveInitializedEvent.InputTuple,
    CollectiveInitializedEvent.OutputTuple,
    CollectiveInitializedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MemberRemoved"
  ): TypedContractEvent<
    MemberRemovedEvent.InputTuple,
    MemberRemovedEvent.OutputTuple,
    MemberRemovedEvent.OutputObject
  >;
  getEvent(
    key: "NewMember"
  ): TypedContractEvent<
    NewMemberEvent.InputTuple,
    NewMemberEvent.OutputTuple,
    NewMemberEvent.OutputObject
  >;
  getEvent(
    key: "OperatorRenounced"
  ): TypedContractEvent<
    OperatorRenouncedEvent.InputTuple,
    OperatorRenouncedEvent.OutputTuple,
    OperatorRenouncedEvent.OutputObject
  >;
  getEvent(
    key: "PoolAdded"
  ): TypedContractEvent<
    PoolAddedEvent.InputTuple,
    PoolAddedEvent.OutputTuple,
    PoolAddedEvent.OutputObject
  >;
  getEvent(
    key: "RewardForwarded"
  ): TypedContractEvent<
    RewardForwardedEvent.InputTuple,
    RewardForwardedEvent.OutputTuple,
    RewardForwardedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "CWalletSet(address)": TypedContractEvent<
      CWalletSetEvent.InputTuple,
      CWalletSetEvent.OutputTuple,
      CWalletSetEvent.OutputObject
    >;
    CWalletSet: TypedContractEvent<
      CWalletSetEvent.InputTuple,
      CWalletSetEvent.OutputTuple,
      CWalletSetEvent.OutputObject
    >;

    "CollectiveInitialized(address,address)": TypedContractEvent<
      CollectiveInitializedEvent.InputTuple,
      CollectiveInitializedEvent.OutputTuple,
      CollectiveInitializedEvent.OutputObject
    >;
    CollectiveInitialized: TypedContractEvent<
      CollectiveInitializedEvent.InputTuple,
      CollectiveInitializedEvent.OutputTuple,
      CollectiveInitializedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MemberRemoved(address)": TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;
    MemberRemoved: TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;

    "NewMember(address)": TypedContractEvent<
      NewMemberEvent.InputTuple,
      NewMemberEvent.OutputTuple,
      NewMemberEvent.OutputObject
    >;
    NewMember: TypedContractEvent<
      NewMemberEvent.InputTuple,
      NewMemberEvent.OutputTuple,
      NewMemberEvent.OutputObject
    >;

    "OperatorRenounced(address)": TypedContractEvent<
      OperatorRenouncedEvent.InputTuple,
      OperatorRenouncedEvent.OutputTuple,
      OperatorRenouncedEvent.OutputObject
    >;
    OperatorRenounced: TypedContractEvent<
      OperatorRenouncedEvent.InputTuple,
      OperatorRenouncedEvent.OutputTuple,
      OperatorRenouncedEvent.OutputObject
    >;

    "PoolAdded(address,address,address,address)": TypedContractEvent<
      PoolAddedEvent.InputTuple,
      PoolAddedEvent.OutputTuple,
      PoolAddedEvent.OutputObject
    >;
    PoolAdded: TypedContractEvent<
      PoolAddedEvent.InputTuple,
      PoolAddedEvent.OutputTuple,
      PoolAddedEvent.OutputObject
    >;

    "RewardForwarded(address,address,uint256,address)": TypedContractEvent<
      RewardForwardedEvent.InputTuple,
      RewardForwardedEvent.OutputTuple,
      RewardForwardedEvent.OutputObject
    >;
    RewardForwarded: TypedContractEvent<
      RewardForwardedEvent.InputTuple,
      RewardForwardedEvent.OutputTuple,
      RewardForwardedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
