/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CWallet } from "./CWallet";
export type { Collective } from "./Collective";
export type { HoneyPot } from "./HoneyPot";
export type { Pool } from "./Pool";
