/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface HoneyPotFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createHoneyPot" | "getHoneyPot" | "honeyPotImplementation"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "HoneyPotCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createHoneyPot",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHoneyPot",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "honeyPotImplementation",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createHoneyPot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHoneyPot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "honeyPotImplementation",
    data: BytesLike
  ): Result;
}

export namespace HoneyPotCreatedEvent {
  export type InputTuple = [honeyPot: AddressLike, operator: AddressLike];
  export type OutputTuple = [honeyPot: string, operator: string];
  export interface OutputObject {
    honeyPot: string;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HoneyPotFactory extends BaseContract {
  connect(runner?: ContractRunner | null): HoneyPotFactory;
  waitForDeployment(): Promise<this>;

  interface: HoneyPotFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createHoneyPot: TypedContractMethod<
    [_operator: AddressLike, _salt: BigNumberish],
    [string],
    "nonpayable"
  >;

  getHoneyPot: TypedContractMethod<
    [_operator: AddressLike, _salt: BigNumberish],
    [string],
    "view"
  >;

  honeyPotImplementation: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createHoneyPot"
  ): TypedContractMethod<
    [_operator: AddressLike, _salt: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getHoneyPot"
  ): TypedContractMethod<
    [_operator: AddressLike, _salt: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "honeyPotImplementation"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "HoneyPotCreated"
  ): TypedContractEvent<
    HoneyPotCreatedEvent.InputTuple,
    HoneyPotCreatedEvent.OutputTuple,
    HoneyPotCreatedEvent.OutputObject
  >;

  filters: {
    "HoneyPotCreated(address,address)": TypedContractEvent<
      HoneyPotCreatedEvent.InputTuple,
      HoneyPotCreatedEvent.OutputTuple,
      HoneyPotCreatedEvent.OutputObject
    >;
    HoneyPotCreated: TypedContractEvent<
      HoneyPotCreatedEvent.InputTuple,
      HoneyPotCreatedEvent.OutputTuple,
      HoneyPotCreatedEvent.OutputObject
    >;
  };
}
